### ISSUE TITLE
Non fixed irrigation and irrigation calculation

### ISSUE THREAD

**Issue by mabbettbyron** [mahalsnz/soilmoisture#174]
Ok, We do not have any rules about the non drip radio button and the irrigation calculation yet.

We will have to come up with them and include them in the spreadsheet of formulas first before making the changes.

---

There will be sites that have non fixed irrigation (overheads or traveling irrigators) that could have a 0 listed but I think the calculation relies on the emitter spacing being set to the same as the tree spacings for this calculation to work so I guess no value should be zero.

In cases like this the non drip radio button is selected so the irrigation calculation changes

**Comment by Brendanfruition** [comment]
Hi Byron,

The non drip radio button will make the 'water meter' reading that is entered as verbose- rainfall. This is because in an irrigation system with no fixed irrigation (overhead irrigation for example) we collect the actual volume applied in water gauges on the ground near the monitoring tubes.

Calculation for 'irrigation mm'
**If (meter-rain>0 then meter-rain+5)**
example with 32mm irrigation and 2mm rain   if(32-2>0 then 32-2+5)  =  **35mm** 

The calculation for determining litres per plant is different to that used for 'drip'
Looks something like this.

**'Irrigation mm' x (rowspace x plant space)**

Example continuing from above figures
  35mm x (4.5m x2.5m)=  **393 liters per tree**

Hope this  makes sense.

Cheers
Brendan

**Comment by mabbettbyron** [comment]
**All Done I think. 5 hours.**

**Comment by Brendanfruition** [comment]
Hey

This is looking good, I will keep checking the numbers for the next week or so.

Cheers
