### ISSUE TITLE
Terraprobe/ hortplus not giving full/ refill points

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#188]
Hi Byron,
From Millar as below, not sure what we should look at in Terraprobe admin for this?
Cheers

Brendan

![graph](https://user-images.githubusercontent.com/50975792/95908118-0feadc80-0df9-11eb-982e-48160f24bc39.png)

Hi Angus,

I just looked through the network response from Terraprobe, it's not actually giving us a refill or full point reading.

I'm not sure if this is something that needs to be reviewed in Terraprobe like regular monitoring records?

Cheers,
Millar

On Tue, Oct 13, 2020 at 4:16 PM Angus Bews <AngusBews@fruition.net.nz> wrote:
Hey Millar,
T&G Willapple: 650 JZ1
                                649 Envy 1
They are new sites
 
Cheers,
 
Angus Bews
Horticultural Technician
Fruition Horticulture HB
(021 949 906)

**Comment by mabbettbyron** [comment]
Hi Guys, This is because the refill and full point readings have not been reviewed, which is a bit annoying. If you manually set them to reviewed they will appear in Portal.

If you are creating new fp or refill set them to reviewed. When we bring them into a new season, they will be created as reviewed.
